package com.example.stockwatch_assistant.model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp

data class StockMeta(
    // Auth information
    var name: String = "",
    var ownerUid: String = "",
    // Text
    var text: String = "",
    var pictureUUIDs: List<String> = listOf(),
    // Written on the server
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // FirestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""

)
